"""The version the app actually ships with.

`ios/JobPilot/Info.plist` is generated by XcodeGen and gitignored, so the only
place the shipped version can be pinned is `project.yml`. Two settings there
look like they do it and don't: `MARKETING_VERSION` and
`CURRENT_PROJECT_VERSION` are build settings, and unless the plist *references*
them, XcodeGen writes its own defaults — "1.0" and "1" — into every build.

That's a quiet failure. Bumping the version reads as done, the archive carries
the old numbers, and TestFlight rejects the upload as a duplicate build number
(or worse, accepts it and labels five features as 1.0).
"""
from __future__ import annotations

import pathlib
import re

PROJECT = (pathlib.Path(__file__).resolve().parents[1] / "ios/project.yml").read_text()


def _setting(name: str) -> str | None:
    m = re.search(rf"^\s*{name}:\s*\"?([^\"\n#]+)\"?\s*$", PROJECT, re.M)
    return m.group(1).strip() if m else None


def test_the_plist_takes_its_version_from_the_build_settings():
    """Without these the bump above them is decoration."""
    assert _setting("CFBundleShortVersionString") == "$(MARKETING_VERSION)"
    assert _setting("CFBundleVersion") == "$(CURRENT_PROJECT_VERSION)"


def test_the_build_number_has_moved_past_the_first_upload():
    """TestFlight refuses a build number it has already seen."""
    build = _setting("CURRENT_PROJECT_VERSION")
    assert build and build.isdigit(), build
    assert int(build) >= 2, "still on the very first build number"


def test_the_marketing_version_is_a_version():
    version = _setting("MARKETING_VERSION")
    assert version and re.fullmatch(r"\d+\.\d+(\.\d+)?", version), version
